export const json1 = [
  {
    "RequestID": 2,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Create)",
    "Role": "Requester2",
    "BusinessProcess_Prev": "",
    "Scenario_Prev": "",
    "Reole_Prev": "",
    "StartedOn": "5/30/2022",
    "FinishedOn": "6/9/2022",
    "FinishedBy": "FColasa",
    "DurationMinutes": 4662,
    "Duration": "8 Days,  5 Hrs, 42 Mins",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 3,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Create)",
    "Role": "JBS2",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Requester2",
    "StartedOn": "6/9/2022",
    "FinishedOn": "6/10/2022",
    "FinishedBy": "DPIEDFOR",
    "DurationMinutes": 440,
    "Duration": "0 Days,  7 Hrs, 20 Mins",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 1007599,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Create)",
    "Role": "Requester",
    "BusinessProcess_Prev": "",
    "Scenario_Prev": "",
    "Reole_Prev": "",
    "StartedOn": "5/30/2022",
    "FinishedOn": "6/9/2022",
    "FinishedBy": "FColasa",
    "DurationMinutes": 4662,
    "Duration": "8 Days,  5 Hrs, 42 Mins",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 1007599,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Create)",
    "Role": "JBS",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Requester",
    "StartedOn": "6/9/2022",
    "FinishedOn": "6/10/2022",
    "FinishedBy": "DPIEDFOR",
    "DurationMinutes": 440,
    "Duration": "0 Days,  7 Hrs, 20 Mins",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 1007599,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Create)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "JBS",
    "StartedOn": "6/10/2022",
    "FinishedOn": "6/10/2022",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "0 Days,  0 Hrs,  1 Min",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "JBS",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Post",
    "StartedOn": "6/10/2022",
    "FinishedOn": "6/10/2022",
    "FinishedBy": "DPIEDFOR",
    "DurationMinutes": 1,
    "Duration": "0 Days,  0 Hrs,  1 Min",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Deliver EDN",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Post",
    "StartedOn": "6/10/2022",
    "FinishedOn": "6/13/2022",
    "FinishedBy": "pkilaru",
    "DurationMinutes": 162,
    "Duration": "0 Days,  2 Hrs, 42 Mins",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Data Ops",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Post",
    "StartedOn": "6/10/2022",
    "FinishedOn": "6/13/2022",
    "FinishedBy": "AB3",
    "DurationMinutes": 418,
    "Duration": "0 Days,  6 Hrs, 58 Mins",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "BOM",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Post",
    "StartedOn": "6/10/2022",
    "FinishedOn": "8/1/2022",
    "FinishedBy": "process",
    "DurationMinutes": 19028,
    "Duration": "35 Days,  2 Hrs,  8 Mins",
    "System": "EU2",
    "State": "Completed"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Deliver Trans",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "JBS",
    "StartedOn": "6/13/2022",
    "FinishedOn": "6/17/2022",
    "FinishedBy": "JSCHELL",
    "DurationMinutes": 2540,
    "Duration": "4 Days,  6 Hrs, 20 Mins",
    "System": "EU2",
    "State": "InProgress"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Deliver Trans",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Deliver EDN",
    "StartedOn": "6/13/2022",
    "FinishedOn": "6/17/2022",
    "FinishedBy": "JSCHELL",
    "DurationMinutes": 2540,
    "Duration": "4 Days,  6 Hrs, 20 Mins",
    "System": "EU2",
    "State": "InProgress"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Planner",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "JBS2",
    "StartedOn": "6/13/2022",
    "FinishedOn": "8/1/2022",
    "FinishedBy": "GRaja2",
    "DurationMinutes": 18866,
    "Duration": "34 Days,  8 Hrs, 26 Mins",
    "System": "EU2",
    "State": "InProgress"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Planner",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Deliver EDN",
    "StartedOn": "6/13/2022",
    "FinishedOn": "8/1/2022",
    "FinishedBy": "GRaja2",
    "DurationMinutes": 18866,
    "Duration": "34 Days,  8 Hrs, 26 Mins",
    "System": "EU2",
    "State": "InProgress"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Deliver Trans",
    "StartedOn": "8/1/2022",
    "FinishedOn": "8/1/2022",
    "FinishedBy": "ELUCANTO",
    "DurationMinutes": 189,
    "Duration": "0 Days,  3 Hrs,  9 Mins",
    "System": "EU2",
    "State": "Upcoming"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Planner",
    "StartedOn": "8/1/2022",
    "FinishedOn": "8/1/2022",
    "FinishedBy": "ELUCANTO",
    "DurationMinutes": 189,
    "Duration": "0 Days,  3 Hrs,  9 Mins",
    "System": "EU2",
    "State": "Upcoming"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Data Ops",
    "StartedOn": "8/1/2022",
    "FinishedOn": "8/1/2022",
    "FinishedBy": "ELUCANTO",
    "DurationMinutes": 189,
    "Duration": "0 Days,  3 Hrs,  9 Mins",
    "System": "EU2",
    "State": "Upcoming"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "BOM",
    "StartedOn": "8/1/2022",
    "FinishedOn": "8/1/2022",
    "FinishedBy": "ELUCANTO",
    "DurationMinutes": 189,
    "Duration": "0 Days,  3 Hrs,  9 Mins",
    "System": "EU2",
    "State": "Upcoming"
  },
  {
    "RequestID": 1008230,
    "RequestID_Previous": 1007599,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "MD Reviewer",
    "StartedOn": "8/1/2022",
    "FinishedOn": "8/1/2022",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "0 Days,  0 Hrs,  1 Min",
    "System": "EU2",
    "State": "Upcoming"
  },
  {
    "RequestID": 1010624,
    "RequestID_Previous": 1008230,
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan External)",
    "Role": "JBS",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Post",
    "StartedOn": "8/1/2022",
    "FinishedOn": "8/2/2022",
    "FinishedBy": "ADVOCHT",
    "DurationMinutes": 590,
    "Duration": "1 Day,   0 Hrs, 50 Mins",
    "System": "EU2",
    "State": "Upcoming"
  }
];

export const json2 = [
  {
    "RequestID": 1010467,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 1)",
    "Role": "Local MD",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Quality External",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:17",
    "FinishedOn": "10/12/2023 17:17",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023",
  },
  {
    "RequestID": 1010467,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 1)",
    "Role": "Make Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "BOM - Make1",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:16",
    "FinishedOn": "10/12/2023 17:16",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010467,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 1)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Local MD",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:17",
    "FinishedOn": "10/12/2023 17:18",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010467,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 1)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "MD Reviewer",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:18",
    "FinishedOn": "10/12/2023 17:19",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010467,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 1)",
    "Role": "Quality External",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Make Reviewer",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:16",
    "FinishedOn": "10/12/2023 17:17",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Affiliate",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:25",
    "FinishedOn": "10/12/2023 17:26",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "DI&T",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:28",
    "FinishedOn": "10/12/2023 17:28",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "EH&S",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:26",
    "FinishedOn": "10/12/2023 17:27",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Local MD",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/13/2023 20:59",
    "FinishedOn": "10/12/2023 17:28",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Planner",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:20",
    "FinishedOn": "10/12/2023 17:25",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Quality External",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:25",
    "FinishedOn": "10/12/2023 17:28",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Trade",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 1)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:20",
    "FinishedOn": "10/12/2023 17:28",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "CMC Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Affiliate",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/14/2023 17:20",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Distribution Finance",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Planner",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:28",
    "FinishedOn": "10/12/2023 17:25",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Manufacturing Finance",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Planner",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:27",
    "FinishedOn": "10/12/2023 17:28",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "CMC Reviewer",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "DI&T",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Distribution Finance",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Manufacturing Finance",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "QA EDN",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Quality",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Sourcing Finance",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Trade",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Warehouse",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "QA Reviewer",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "QA EDN",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Local MD",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/14/2023 17:20",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "QA Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "MD Reviewer",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Quality",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Quality External",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:28",
    "FinishedOn": "10/13/2023 20:59",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Sourcing Finance",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Planner",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:25",
    "FinishedOn": "10/12/2023 17:25",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010468,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 2)",
    "Role": "Warehouse",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "EH&S",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:28",
    "FinishedOn": "10/12/2023 17:28",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "DI&T",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Distribution Finance",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Local MD",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Manufacturing Finance",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 10,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Serialization Team",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 2)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 14918,
    "Duration": "27 Days",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Distribution Finance Final",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Distribution Finance Review",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Distribution Finance Review",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Distribution Finance",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Manufacturing Finance Final",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Manufacturing Finance Review",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Manufacturing Finance Review",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Manufacturing Finance",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "QA Reviewer",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 4,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "QA Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Distribution Finance Final",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "QA Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Local MD",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "QA Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Serialization Team",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "QA Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Sourcing Finance Final",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Sourcing Finance",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Manufacturing Finance Final",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Sourcing Finance Final",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Sourcing Finance Review",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": "NULL",
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 3)",
    "Role": "Sourcing Finance Review",
    "BusinessProcess_Prev": "Finished Good (Made) - Change (Make)",
    "Scenario_Prev": "Finished Good (Made) - Change (Make 3)",
    "Reole_Prev": "Sourcing Finance",
    "Material": "0991JW",
    "Material_Description": "NULL",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "NULL",
    "FinishedOn": "NULL",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010467,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - Change (Make)",
    "Scenario": "Finished Good (Made) - Change (Make 1)",
    "Role": "BOM - Make1",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan External)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:14",
    "FinishedOn": "10/12/2023 17:16",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010464,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Create)",
    "Role": "Requester",
    "BusinessProcess_Prev": "",
    "Scenario_Prev": "",
    "Reole_Prev": "",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 16:46",
    "FinishedOn": "10/12/2023 16:49",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 176962,
    "Duration": "327 Days",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010464,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Create)",
    "Role": "JBS",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Requester",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 16:49",
    "FinishedOn": "10/12/2023 16:51",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010464,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Create)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "JBS",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 16:51",
    "FinishedOn": "10/12/2023 16:53",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010466,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan External)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan External)",
    "Reole_Prev": "Data Ops",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:10",
    "FinishedOn": "10/12/2023 17:11",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010466,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan External)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan External)",
    "Reole_Prev": "JBS",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:10",
    "FinishedOn": "10/12/2023 17:11",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010466,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan External)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan External)",
    "Reole_Prev": "Local MD",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:10",
    "FinishedOn": "10/12/2023 17:11",
    "FinishedBy": "process",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010466,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan External)",
    "Role": "Data Ops",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:09",
    "FinishedOn": "10/12/2023 17:09",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010466,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan External)",
    "Role": "JBS",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:07",
    "FinishedOn": "10/12/2023 17:09",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 176980,
    "Duration": "327 Days",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010466,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan External)",
    "Role": "Local MD",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 17:09",
    "FinishedOn": "10/12/2023 17:10",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Data Ops",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:03",
    "FinishedOn": "10/12/2023 19:06",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Deliver EDN",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 16:54",
    "FinishedOn": "10/12/2023 19:00",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 176970,
    "Duration": "327 Days",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "JBS",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Create)",
    "Reole_Prev": "Post",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 16:54",
    "FinishedOn": "10/12/2023 19:04",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 176970,
    "Duration": "327 Days",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "BOM",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "EPL Planner",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:03",
    "FinishedOn": "10/12/2023 19:03",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Deliver Trans",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Deliver EDN",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:04",
    "FinishedOn": "10/12/2023 19:05",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "EPL Planner",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Site Planner",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:02",
    "FinishedOn": "10/12/2023 19:03",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "BOM",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:06",
    "FinishedOn": "10/12/2023 19:36",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Data Ops",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:06",
    "FinishedOn": "10/12/2023 19:36",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Deliver Trans",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:06",
    "FinishedOn": "10/12/2023 19:36",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "MD Reviewer",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "JBS",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:06",
    "FinishedOn": "10/12/2023 19:36",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 1,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Post",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "MD Reviewer",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:36",
    "FinishedOn": "10/13/2023 21:25",
    "FinishedBy": "process",
    "DurationMinutes": 2,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "Site Planner",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "SNP Planner",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:05",
    "FinishedOn": "10/12/2023 19:02",
    "FinishedBy": "jwhite47",
    "DurationMinutes": 4,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  },
  {
    "RequestID": 1010465,
    "RequestID_Previous": "",
    "BusinessProcess": "Finished Good (Made) - New (Create > Plan)",
    "Scenario": "Finished Good (Made) - New (Plan)",
    "Role": "SNP Planner",
    "BusinessProcess_Prev": "Finished Good (Made) - New (Create > Plan)",
    "Scenario_Prev": "Finished Good (Made) - New (Plan)",
    "Reole_Prev": "Deliver EDN",
    "Material": "0991JW",
    "Material_Description": "EndtoEnd05",
    "Material_Type": "",
    "plant": "BEP6",
    "plant_name": "Manufacturing Beerse",
    "StartedOn": "10/12/2023 19:04",
    "FinishedOn": "10/12/2023 19:00",
    "FinishedBy": "process",
    "DurationMinutes": 0,
    "Duration": "1 Day",
    "System": "EU2",
    "RefreshedOn": "8/2/2023"
  }
];

// json2.sort((a, b) => {
//   if (a.RequestID === 'NULL' && b.RequestID === 'NULL') {
//     return 0;
//   } else if (a.RequestID === 'NULL') {
//     return 1;
//   } else if (b.RequestID === 'NULL') {
//     return -1;
//   }
  
//   return a.RequestID - b.RequestID;
// });
export const jsonData = parseDate(json2);
//export const jsonData = json1;

function parseDate(data) {
  data.forEach(element => {
    Date.parse(element.StartedOn)
    const start = element.StartedOn;
    const end = element.FinishedOn;
    if (isValidDate(start) && isValidDate(end)) {
      element.State = 'Completed'
    } else if (isValidDate(start) && !isValidDate(end)) {
      element.State = 'InProgress'
    } else if (!isValidDate(start) && !isValidDate(end)) {
      element.State = 'Upcoming'
    } else {
      element.State = 'Unknown'
    }
  });
  return data;
}

function isValidDate(dateString) {
  // Attempt to create a Date object from the input string
  const dateObject = new Date(dateString);

  // Check if the dateObject is not 'Invalid Date' and the input string is a valid date
  return !isNaN(dateObject) && dateObject.toString() !== 'Invalid Date';
}